/**
 * Plan and execute a genre-folder reorganization.
 *
 * Flow:
 *   1. Pick a source — either an analysis.json on disk, or the tracks
 *      currently loaded in the library.
 *   2. Tweak min-genre-size / use-subgenres / target-root.
 *   3. Click "Preview" — UI shows the move plan grouped by destination.
 *   4. Click "Execute" — actually moves the files.
 */

import { useEffect, useMemo, useRef, useState } from "react";
import {
  FolderTree, FolderOpen, Play, Eye, AlertCircle, ArrowRight, FileJson,
  CheckCircle2, RotateCcw, Undo2, Loader2,
} from "lucide-react";
import { open as openDialog, save as saveDialog } from "@tauri-apps/plugin-dialog";

import {
  useConfigStore, useLibraryStore, useNotificationStore, useOperationStore, useUIStore,
} from "../stores";
import { rpc, isCancellation } from "../hooks/useSidecar";
import { revertJournal, pruneEmptyFolders } from "../api/rpc";
import type { PruneEmptyFoldersResponse } from "../api/methods";
import type { OrganizePlan, PlannedMove as GeneratedPlannedMove } from "../types";
import { TagBadge } from "./TagBadges";
import { ConfirmModal } from "./ConfirmModal";

// Local extension of the generated PlannedMove dataclass. The Python side now
// emits `relative_destination` but the generated TS type is
// regenerated by a separate codegen step we don't own here, so we declare it
// inline as optional and use it wherever it's present.
type PlannedMove = GeneratedPlannedMove & { relative_destination?: string };

/** Hard cap on min_genre_size. 500 covers all realistic libraries — anything
 * higher is the user typo'ing and ending up with everything in Other/. */
const MAX_MIN_GENRE_SIZE = 500;
/** Above this, show a soft warning but don't block — power users may want it. */
const MIN_GENRE_SIZE_WARN_AT = 100;
/** If fewer than this fraction of tracks have ml_genre, warn the user that
 * organize will route most of them to Unknown/. 0.5 == "less than half". */
const ML_GENRE_COVERAGE_WARN_THRESHOLD = 0.5;

type Source =
  | { kind: "in-memory" }
  | { kind: "file"; path: string }
  | null;

/** Result of a completed organize run, captured for the result panel. */
interface OrganizeResult {
  baseDir: string;
  planned: number;
  moved: number;
  errors: string[];
  /** path of the tag backup we created first, if any */
  backupPath: string | null;
  /** destination-folder → number of files moved into it */
  folderCounts: [string, number][];
  /** undo-journal path for this run (null if nothing moved / journal failed) */
  journalPath: string | null;
  /** folders this run emptied — candidates for pruning, nothing removed yet */
  emptiedDirs: string[];
}

export function OrganizeView() {
  const tracks = useLibraryStore((s) => s.tracks);
  const libraryPath = useLibraryStore((s) => s.libraryPath);
  const updateTrackPaths = useLibraryStore((s) => s.updateTrackPaths);

  const active = useOperationStore((s) => s.active);
  const begin = useOperationStore((s) => s.begin);
  const finish = useOperationStore((s) => s.finish);
  const fail = useOperationStore((s) => s.fail);
  const errorMsg = useOperationStore((s) => s.error);

  const plan = useOperationStore((s) => s.organizePlan);
  const setPlan = useOperationStore((s) => s.setOrganizePlan);

  const orgCfg = useConfigStore((s) => s.config.organization);
  const updateOrganization = useConfigStore((s) => s.updateOrganization);

  const notify = useNotificationStore((s) => s.notify);

  const [source, setSource] = useState<Source>(
    tracks.length > 0 ? { kind: "in-memory" } : null,
  );
  const [showConfirm, setShowConfirm] = useState(false);
  const [backupFirst, setBackupFirst] = useState(true);
  const [result, setResult] = useState<OrganizeResult | null>(null);
  // Local validation state for the target_root input. `validating` gates the
  // Preview button while we're waiting on the sidecar's writability probe.
  const [targetError, setTargetError] = useState<string | null>(null);
  const [targetWarnings, setTargetWarnings] = useState<string[]>([]);
  const [validatingTarget, setValidatingTarget] = useState(false);
  // Guards against double-clicking Execute and opening two confirm modals
  // before the first one's confirm callback finishes.
  const confirmingRef = useRef(false);
  // Capture the params used to build the current plan so we can show a
  // "stale" warning when the user edits config without re-previewing.
  const [planParams, setPlanParams] = useState<string | null>(null);

  const setViewMode = useUIStore((s) => s.setViewMode);

  // Fingerprint of the params that flow into plan_organization. Updates to
  // Cheap content fingerprint of the fields that actually drive the organize
  // plan: each track's path + ML genre + subgenre. Counting `tracks.length`
  // alone was insufficient — a track whose genre changed (e.g. a re-analyze
  // updated ML fields without changing the file count) would leave the
  // previewed plan looking valid while the executed moves silently diverge.
  // Since organize is a destructive, no-undo file move, the confirmed preview
  // MUST match what executes. Recomputed only when `tracks` identity changes
  // (setTracks / mergeAnalyzedTrack), so it's O(n) once per change, not per
  // render.
  const tracksFingerprint = useMemo(() => {
    if (source?.kind !== "in-memory") return "";
    let h = 0;
    for (const t of tracks) {
      const s = `${t.path}|${t.ml_analysis?.ml_genre ?? ""}|${t.ml_analysis?.ml_subgenre ?? ""}`;
      // djb2-ish rolling hash — cheap, order-sensitive, collision-resistant
      // enough to detect content drift between preview and execute.
      for (let i = 0; i < s.length; i++) {
        h = (h * 33 + s.charCodeAt(i)) | 0;
      }
    }
    return `${tracks.length}:${h}`;
  }, [tracks, source?.kind]);

  // any of these invalidate a previously-generated plan.
  const currentParamsKey = useMemo(() => {
    return JSON.stringify({
      use_subgenres: orgCfg.use_subgenres,
      min_genre_size: orgCfg.min_genre_size,
      target_root: orgCfg.target_root ?? null,
      source:
        source?.kind === "file"
          ? { kind: "file", path: source.path }
          : source?.kind === "in-memory"
            ? { kind: "in-memory", fingerprint: tracksFingerprint }
            : null,
    });
  }, [orgCfg.use_subgenres, orgCfg.min_genre_size, orgCfg.target_root, source, tracksFingerprint]);

  // Drop a stale plan as soon as the user changes any input that feeds into
  // it. Cleaner than showing a "this plan is stale" banner — the user
  // re-clicks Preview and sees fresh counts.
  useEffect(() => {
    if (plan && planParams && planParams !== currentParamsKey) {
      setPlan(null);
      setPlanParams(null);
    }
  }, [currentParamsKey, plan, planParams, setPlan]);

  // ML-genre coverage check — disables Execute when most tracks lack a genre.
  // Counts tracks in the currently-loaded library only; we can't
  // peek inside a file-source analysis.json without loading it.
  const mlCoverage = useMemo(() => {
    if (source?.kind !== "in-memory") return null;
    if (tracks.length === 0) return null;
    let withGenre = 0;
    for (const t of tracks) {
      if (t.ml_analysis?.ml_genre) withGenre++;
    }
    return {
      total: tracks.length,
      withGenre,
      fraction: withGenre / tracks.length,
    };
  }, [source, tracks]);

  const lowCoverageWarning = useMemo(() => {
    if (!mlCoverage) return null;
    if (mlCoverage.fraction >= ML_GENRE_COVERAGE_WARN_THRESHOLD) return null;
    const pct = Math.round(mlCoverage.fraction * 100);
    return (
      `Only ${mlCoverage.withGenre} of ${mlCoverage.total} tracks (${pct}%) have ML ` +
      `genre data. The rest will be routed to Unknown/. ` +
      `Run Analyze in the Library tab first for better results.`
    );
  }, [mlCoverage]);

  const handlePickAnalysisFile = async () => {
    const path = await openDialog({
      directory: false,
      multiple: false,
      filters: [{ name: "Analysis JSON", extensions: ["json"] }],
    });
    if (typeof path === "string") setSource({ kind: "file", path });
  };

  const handlePickTargetRoot = async () => {
    const path = await openDialog({ directory: true, multiple: false });
    if (typeof path === "string") {
      updateOrganization({ target_root: path });
      // Re-validate as soon as the picker returns. Folder picker always
      // returns an absolute path, so this mainly catches the cloud-sync
      // warning case + the same-as-source path check.
      validateTarget(path);
    }
  };

  // Pure client-side validation of `target_root`. Catches the common foot-
  // guns (relative path → silent landing in sidecar
  // CWD, same-as-source path, cloud-sync target). Full writability probing
  // is left to the sidecar's _plan_organization step — that's where the
  // mkdir would happen for real anyway, and any PermissionError surfaces
  // there with a useful filesystem error.
  const validateTarget = (value: string | null | undefined) => {
    const trimmed = (value ?? "").trim();
    if (!trimmed) {
      // Empty == "use default", which is the loaded library's own root (the
      // sidecar anchors there via library_path). Always valid.
      setTargetError(null);
      setTargetWarnings([]);
      return;
    }
    setValidatingTarget(true);
    try {
      const error = clientValidateTarget(trimmed);
      setTargetError(error);
      setTargetWarnings(error ? [] : detectTargetWarnings(trimmed, libraryPath));
    } finally {
      setValidatingTarget(false);
    }
  };

  const buildParams = () => {
    const base: Record<string, unknown> = {
      use_subgenres: orgCfg.use_subgenres,
      min_genre_size: orgCfg.min_genre_size,
      target_root: orgCfg.target_root,
      // The loaded library's root. With no target_root set, the sidecar anchors
      // the genre tree here instead of guessing from track paths — a guess that
      // lands one level too deep as soon as the library is already sorted.
      library_path: libraryPath,
    };
    if (source?.kind === "file") base.analysis_path = source.path;
    else if (source?.kind === "in-memory") base.analysis = { tracks };
    return base;
  };

  const handlePreview = async () => {
    if (!source) return;
    // Re-validate the target one more time before planning. The on-blur
    // validator covers normal flow, but a user can edit and immediately hit
    // Preview without triggering blur (Enter, keyboard nav, etc.).
    if (orgCfg.target_root && orgCfg.target_root.trim()) {
      const error = clientValidateTarget(orgCfg.target_root.trim());
      if (error) {
        setTargetError(error);
        setTargetWarnings([]);
        return;
      }
    }
    begin("organize");
    try {
      const result = await rpc<OrganizePlan>("plan_organization", buildParams());
      setPlan(result);
      setPlanParams(currentParamsKey);
      finish();
    } catch (e) {
      fail(e);
    }
  };

  const handleExecuteClick = () => {
    if (!plan || plan.moves.length === 0) return;
    // Guard: a double-click would otherwise open two confirm modals back to
    // back, each of which kicks off its own performExecute on confirm.
    if (confirmingRef.current || showConfirm) return;
    confirmingRef.current = true;
    setShowConfirm(true);
  };

  const closeConfirm = () => {
    setShowConfirm(false);
    confirmingRef.current = false;
  };

  const performExecute = async () => {
    closeConfirm();
    if (!plan) return;

    // Optionally back up tags first so the user has a restore path
    let backupPath: string | null = null;
    if (backupFirst) {
      const out = await saveDialog({
        defaultPath: "tags_backup_pre_organize.json",
        filters: [{ name: "Tag backup (JSON)", extensions: ["json"] }],
      });
      if (typeof out !== "string") {
        // User cancelled the OS save dialog. This is indistinguishable from
        // the "I changed my mind, don't organize" case, so be loud about it:
        // tell them organize did NOT run, and leave the plan intact so they
        // can re-click Execute (or uncheck "back up tags first").
        notify("Backup cancelled. Organize did not run.", { kind: "info" });
        return;
      }
      backupPath = out;
      const backupOpId = begin("backup");
      try {
        await rpc("backup_tags", { path: plan.base_dir, output_path: out, op_id: backupOpId });
        finish();
      } catch (e) {
        fail(e);
        return;
      }
    }

    // Capture the planned destinations before we mutate `plan`
    const capturedPlan = plan;

    const opId = begin("organize");
    try {
      const stats = await rpc<{
        planned: number; moved: number; errors: string[]; journal_path: string | null;
        moved_pairs?: string[][];
        cancelled?: boolean;
        /** Optional: an older sidecar doesn't send it. */
        emptied_dirs?: string[];
      }>(
        "organize",
        { ...buildParams(), dry_run: false, op_id: opId },
      );
      finish();

      // Build a destination-folder breakdown from the captured plan. Prefer
      // the server-computed `relative_destination` over local string-arithmetic
      // (which breaks on Windows case / sep mismatch). Falls back
      // to a defensive split if the field is missing from an older sidecar.
      const folderCounts = new Map<string, number>();
      for (const move of capturedPlan.moves) {
        const folder = folderForMove(move, capturedPlan.base_dir);
        folderCounts.set(folder, (folderCounts.get(folder) ?? 0) + 1);
      }

      // Sync the library store: each successful move means the on-disk path
      // changed. Without this, the next time the user clicks Show in Folder /
      // Play / Re-tag we'd FileNotFoundError against the old path.
      //
      // CRITICAL: map from the sidecar's ACTUAL moved pairs, never the plan —
      // (a) a cancelled/partly-failed run moved only a subset (mapping the
      // whole plan pointed unmoved tracks at phantom destinations), and (b)
      // the real destination can differ from the planned one (re-uniquified at
      // execute time to avoid clobbering an existing file). The plan fallback
      // only covers an older sidecar that doesn't send moved_pairs, and only
      // for clean, complete runs.
      const pathMap = new Map<string, string>();
      if (stats.moved_pairs) {
        for (const [src, dst] of stats.moved_pairs) {
          pathMap.set(src, dst);
        }
      } else if (!stats.cancelled && stats.errors.length === 0) {
        for (const move of capturedPlan.moves) {
          pathMap.set(move.source, move.destination);
        }
      }
      updateTrackPaths(pathMap);

      setResult({
        baseDir: capturedPlan.base_dir,
        planned: stats.planned,
        moved: stats.moved,
        errors: stats.errors,
        backupPath,
        folderCounts: [...folderCounts.entries()].sort((a, b) => b[1] - a[1]),
        journalPath: stats.journal_path ?? null,
        emptiedDirs: stats.emptied_dirs ?? [],
      });
      setPlan(null);
      setPlanParams(null);

      // Brief notification too, in case the user navigated away mid-op. A
      // cancelled run still moved some files and left an undo journal — say so
      // rather than claiming a clean success.
      notify(
        stats.cancelled
          ? `Organize cancelled — moved ${stats.moved} of ${stats.planned} before stopping. Undo is available.`
          : `Moved ${stats.moved} of ${stats.planned} files`,
        { kind: stats.cancelled || stats.errors.length > 0 ? "info" : "success" },
      );
    } catch (e) {
      fail(e);
    }
  };

  const handleOrganizeAnother = () => {
    setResult(null);
    setSource(tracks.length > 0 ? { kind: "in-memory" } : null);
  };

  // When we have a completed-run result, replace the whole view with a
  // recap so the user actually reads what changed.
  if (result) {
    return (
      <OrganizeResultPanel
        result={result}
        onViewLibrary={() => setViewMode("library")}
        onAnother={handleOrganizeAnother}
      />
    );
  }

  return (
    <div className="h-full flex flex-col">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-white/5">
        <div>
          <h1 className="font-display font-semibold text-white">Organize</h1>
          <p className="text-xs text-white/40 truncate max-w-md">
            {plan ? plan.base_dir : "no plan yet"}
          </p>
        </div>
        <div className="flex items-center gap-2">
          {plan && (
            <button
              className="btn-primary"
              onClick={handleExecuteClick}
              // showConfirm guard prevents a double-click from opening two
              // confirm modals before the first has shown its dialog.
              disabled={active !== null || plan.moves.length === 0 || showConfirm}
            >
              <Play className="w-4 h-4" />
              Execute ({plan.moves.length} moves)
            </button>
          )}
        </div>
      </div>

      {errorMsg && (
        <div className="m-4 panel-pad text-sm text-accent-red flex gap-2">
          <AlertCircle className="w-4 h-4 flex-none mt-0.5" />
          <div className="break-words">{errorMsg}</div>
        </div>
      )}

      <div className="flex-1 overflow-auto px-4 py-4">
        {/* Source picker */}
        <Section title="Source" subtitle="Where do the ML genre labels come from?">
          <SourcePicker
            source={source}
            inMemoryAvailable={tracks.length}
            onUseInMemory={() => setSource({ kind: "in-memory" })}
            onPickFile={handlePickAnalysisFile}
          />
        </Section>

        {/* ML-genre coverage warning — fast scan / partial analysis would
            otherwise quietly route everything into Unknown/. */}
        {lowCoverageWarning && (
          <div className="mb-4 panel-pad text-sm text-accent-yellow flex gap-2">
            <AlertCircle className="w-4 h-4 flex-none mt-0.5" />
            <div>{lowCoverageWarning}</div>
          </div>
        )}

        {/* Rules */}
        <Section title="Rules" subtitle="How the folder tree looks">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <div className="label">Min tracks per genre folder</div>
              <input
                type="number"
                min={1}
                max={MAX_MIN_GENRE_SIZE}
                className="input w-24"
                title={`1–${MAX_MIN_GENRE_SIZE}. Higher values send more genres to Other/.`}
                value={orgCfg.min_genre_size}
                onChange={(e) => {
                  // Clamp to a sane range. Without the upper cap, a typo
                  // like 100000 silently turns the whole library into Other/.
                  const raw = Number(e.target.value);
                  const clamped = Math.max(
                    1,
                    Math.min(MAX_MIN_GENRE_SIZE, Number.isFinite(raw) ? raw : 1),
                  );
                  updateOrganization({ min_genre_size: clamped });
                }}
              />
              <div className="text-xs text-white/40 mt-1">
                Rarer genres get bucketed into <code>Other/</code>. Max {MAX_MIN_GENRE_SIZE}.
              </div>
              {orgCfg.min_genre_size >= MIN_GENRE_SIZE_WARN_AT && (
                <div className="text-xs text-accent-yellow mt-1">
                  High value — most genres will probably end up in <code>Other/</code>.
                </div>
              )}
            </div>
            <div>
              <div className="label">Subgenre subfolders</div>
              <label className="flex items-center gap-2 text-sm text-white/80 cursor-pointer">
                <input
                  type="checkbox"
                  checked={orgCfg.use_subgenres}
                  onChange={(e) => updateOrganization({ use_subgenres: e.target.checked })}
                  className="accent-accent"
                />
                Use them
              </label>
              <div className="text-xs text-white/40 mt-1">
                On: <code>House/Deep House/track.mp3</code>. Off: flat <code>House/</code>.
              </div>
            </div>
          </div>

          <div className="mt-4">
            <div className="label">Target root (override)</div>
            <div className="flex gap-2">
              <input
                type="text"
                className={`input flex-1 font-mono text-xs ${targetError ? "border-accent-red/60" : ""}`}
                value={orgCfg.target_root ?? ""}
                placeholder="(default: same parent as analyzed tracks)"
                onChange={(e) => {
                  // Clear stale validation feedback on each keystroke — the
                  // user is in the middle of fixing it. Re-validate on blur.
                  if (targetError) setTargetError(null);
                  if (targetWarnings.length > 0) setTargetWarnings([]);
                  updateOrganization({ target_root: e.target.value });
                }}
                onBlur={(e) => validateTarget(e.target.value)}
              />
              <button
                className="btn-ghost"
                onClick={handlePickTargetRoot}
                aria-label="Choose target root folder"
                title="Choose target root folder"
              >
                <FolderOpen className="w-4 h-4" />
              </button>
            </div>
            {targetError && (
              <div className="mt-1 text-xs text-accent-red flex gap-1.5">
                <AlertCircle className="w-3.5 h-3.5 flex-none mt-0.5" />
                <span>{targetError}</span>
              </div>
            )}
            {targetWarnings.map((w, i) => (
              <div key={i} className="mt-1 text-xs text-accent-yellow flex gap-1.5">
                <AlertCircle className="w-3.5 h-3.5 flex-none mt-0.5" />
                <span>{w}</span>
              </div>
            ))}
          </div>

          <button
            className="btn-primary mt-4"
            onClick={handlePreview}
            disabled={!source || active !== null || validatingTarget || !!targetError}
          >
            <Eye className="w-4 h-4" />
            {validatingTarget ? "Checking target..." : "Preview plan"}
          </button>
        </Section>

        {plan && <PlanPreview plan={plan} />}
      </div>

      <ConfirmModal
        open={showConfirm && !!plan}
        variant="danger"
        destructive
        icon={Play}
        title={plan ? `Move ${plan.moves.length} files?` : "Move files?"}
        message={
          plan && (
            <div className="space-y-2">
              <p>
                Vibechek will move <strong>{plan.moves.length}</strong> files into
                folders under{" "}
                <code className="font-mono text-xs text-white/90">{plan.base_dir}</code>.
              </p>
              <p className="text-xs text-white/60">
                First few moves:
              </p>
              <ul className="text-[11px] font-mono text-white/50 space-y-0.5 max-h-32 overflow-auto">
                {plan.moves.slice(0, 5).map((m) => {
                  // Widen to the extended PlannedMove that carries the optional
                  // `relative_destination` field — see import at top of file.
                  const ext = m as PlannedMove;
                  return (
                    <li key={m.source}>
                      {m.source.split(/[/\\]/).pop()} → {ext.relative_destination || m.destination}
                    </li>
                  );
                })}
                {plan.moves.length > 5 && <li>... and {plan.moves.length - 5} more</li>}
              </ul>
              <p className="text-accent-yellow">Files move immediately. You can undo
                this afterwards — from the result screen or "Recent operations".</p>
            </div>
          )
        }
        extra={
          <label className="flex items-start gap-2 cursor-pointer text-sm text-white/80">
            <input
              type="checkbox"
              checked={backupFirst}
              onChange={(e) => setBackupFirst(e.target.checked)}
              className="mt-0.5 accent-accent"
            />
            <div>
              <div>Back up all tags first <span className="text-xs text-accent-green">(recommended)</span></div>
              <div className="text-xs text-white/50">
                You'll be prompted for a save location. The backup lets you restore tags later if anything looks wrong.
              </div>
            </div>
          </label>
        }
        confirmLabel="Yes, move files"
        cancelLabel="Cancel"
        onConfirm={performExecute}
        onCancel={closeConfirm}
      />
    </div>
  );
}

// ---------------------------------------------------------------------------

function SourcePicker({
  source,
  inMemoryAvailable,
  onUseInMemory,
  onPickFile,
}: {
  source: Source;
  inMemoryAvailable: number;
  onUseInMemory: () => void;
  onPickFile: () => void;
}) {
  return (
    <div className="grid grid-cols-2 gap-3">
      <button
        onClick={onUseInMemory}
        disabled={inMemoryAvailable === 0}
        className={`panel-pad text-left ${
          source?.kind === "in-memory" ? "border-accent/60" : "hover:bg-white/[0.03]"
        } disabled:opacity-50 disabled:cursor-not-allowed`}
      >
        <div className="flex items-center gap-2 text-sm text-white/90">
          <FolderTree className="w-4 h-4 text-accent" />
          Currently loaded library
        </div>
        <div className="text-xs text-white/50 mt-1">
          {inMemoryAvailable > 0
            ? `${inMemoryAvailable} tracks in memory`
            : "Run analyze in the Library tab first."}
        </div>
      </button>

      <button
        onClick={onPickFile}
        className={`panel-pad text-left ${
          source?.kind === "file" ? "border-accent/60" : "hover:bg-white/[0.03]"
        }`}
      >
        <div className="flex items-center gap-2 text-sm text-white/90">
          <FileJson className="w-4 h-4 text-accent" />
          Load analysis.json
        </div>
        <div className="text-xs text-white/50 mt-1 truncate">
          {source?.kind === "file" ? source.path : "Pick a file saved by a previous analyze."}
        </div>
      </button>
    </div>
  );
}

// ---------------------------------------------------------------------------

function PlanPreview({ plan }: { plan: OrganizePlan }) {
  // Group moves by destination folder for a cleaner display. We group on the
  // *relative* path (from base_dir) so folders display consistently regardless
  // of casing / sep mismatches.
  const byDest: Record<string, PlannedMove[]> = {};
  for (const m of plan.moves) {
    const folder = folderForMove(m, plan.base_dir);
    byDest[folder] = byDest[folder] ?? [];
    byDest[folder].push(m);
  }

  const folders = Object.entries(byDest).sort(([a], [b]) => a.localeCompare(b));
  const hasMoves = plan.moves.length > 0;

  return (
    <Section title="Plan" subtitle={`${plan.moves.length} moves planned`}>
      {!hasMoves && (
        <div className="text-sm text-white/50">
          No moves needed — everything is already in the right place.
        </div>
      )}

      {plan.small_genres.length > 0 && (
        <div className="mb-3 text-xs text-white/50">
          Small genres going to <code>Other/</code>:{" "}
          {plan.small_genres.map((g) => (
            <TagBadge key={g} color="neutral">
              {g}
            </TagBadge>
          ))}
        </div>
      )}

      {plan.errors.length > 0 && (
        <div className="mb-3 panel-pad text-xs text-accent-yellow">
          {plan.errors.length} planning issues (first 5 shown):
          <ul className="mt-1 space-y-0.5">
            {plan.errors.slice(0, 5).map((e, i) => (
              <li key={i} className="font-mono">{e}</li>
            ))}
          </ul>
        </div>
      )}

      <div className="space-y-3 max-h-[480px] overflow-auto">
        {folders.map(([folder, moves]) => (
          <FolderGroup key={folder} folder={folder} moves={moves} />
        ))}
      </div>
    </Section>
  );
}

function FolderGroup({
  folder,
  moves,
}: {
  folder: string;
  moves: PlannedMove[];
}) {
  return (
    <div className="panel-pad">
      <div className="flex items-center gap-2 mb-2">
        <FolderTree className="w-4 h-4 text-accent" />
        <div className="text-sm font-medium text-white">
          {folder || "(root)"}
        </div>
        <span className="text-xs text-white/40 ml-auto tabular-nums">{moves.length}</span>
      </div>
      <div className="space-y-1">
        {moves.slice(0, 8).map((m) => (
          <div key={m.source} className="flex items-center gap-2 text-xs text-white/60">
            <ArrowRight className="w-3 h-3 text-white/30 flex-none" />
            <span className="truncate font-mono">{m.source.split(/[/\\]/).pop()}</span>
          </div>
        ))}
        {moves.length > 8 && (
          <div className="text-[11px] text-white/40 pl-5">
            and {moves.length - 8} more...
          </div>
        )}
      </div>
    </div>
  );
}

/**
 * Folder bucket name for a single move. Prefers the server-computed
 * `relative_destination` and falls back to a
 * defensive local split for older sidecar versions. Returns the parent
 * folder of the file, not the file path itself.
 */
function folderForMove(move: PlannedMove, baseDir: string): string {
  // Strip filename → parent folder. Works for both POSIX and Windows seps.
  const stripFilename = (p: string) =>
    p.replace(/[/\\][^/\\]+$/, "") || p;

  const rel = move.relative_destination;
  if (rel && rel !== move.destination) {
    const folder = stripFilename(rel);
    // "." means the file lands directly in base_dir
    return folder === "." || folder === "" ? "(root)" : folder;
  }

  // Fallback path for older sidecar payloads / missing rel field
  const folder = stripFilename(move.destination);
  if (!baseDir) return folder;
  // Case-insensitive prefix match — Windows is case-insensitive but
  // startsWith() isn't. Normalize separators while we're at it.
  const normFolder = folder.replace(/\\/g, "/");
  const normBase = baseDir.replace(/\\/g, "/");
  if (normFolder.toLowerCase().startsWith(normBase.toLowerCase())) {
    const stripped = normFolder.slice(normBase.length).replace(/^\/+/, "");
    return stripped || "(root)";
  }
  return folder;
}

// ---------------------------------------------------------------------------

/**
 * Pure client-side check for `target_root`. Returns an error string for the
 * user, or `null` if the path looks OK. We intentionally do NOT touch the
 * filesystem here — that requires Node-side fs which we don't expose to the
 * renderer. The sidecar's planner does the real mkdir.
 *
 * Catches the footguns:
 *   - Relative paths (would land in sidecar CWD silently)
 *
 * Same-folder-as-source is NOT an error — see `detectTargetWarnings`.
 */
function clientValidateTarget(value: string): string | null {
  // Heuristic absolute-path detection that covers both major shells:
  //   - Windows: drive letter (C:\, D:/) or UNC path (\\server\share)
  //   - POSIX:   leading slash
  // Anything else is treated as relative.
  const isWindowsAbs = /^[a-zA-Z]:[\\/]/.test(value) || /^[\\/][\\/]/.test(value);
  const isPosixAbs = value.startsWith("/");
  if (!isWindowsAbs && !isPosixAbs) {
    return (
      "Target root must be an absolute path " +
      "(e.g. C:\\Music\\sorted on Windows, /Users/you/Music on macOS). " +
      "Use the folder picker to avoid typos."
    );
  }

  // Target == the loaded library is NOT an error: it means "re-organize this
  // library in place", which is how you fix a sorted library after a re-analyze
  // corrects some genres. Only the tracks whose genre changed move. Surfaced as
  // a warning by detectTargetWarnings instead.
  return null;
}

/** True when `value` points at the loaded library itself. */
function isSameFolder(value: string, sourceLibraryPath: string | null): boolean {
  if (!sourceLibraryPath) return false;
  const normalize = (p: string) => p.replace(/[\\/]+$/, "").replace(/\\/g, "/").toLowerCase();
  return normalize(value) === normalize(sourceLibraryPath);
}

/**
 * Best-effort substring check for cloud-sync virtual-FS targets. Mirrors
 * `vibechek.organizer._RISKY_TARGET_SUBSTRINGS` and the sidecar's
 * `_RISKY_PATH_SUBSTRINGS` so we warn before the user organizes a 10k-track
 * library into a OneDrive folder and watches sync re-upload every byte.
 */
function detectTargetWarnings(value: string, sourceLibraryPath: string | null = null): string[] {
  const warnings: string[] = [];

  if (isSameFolder(value, sourceLibraryPath)) {
    warnings.push(
      "Target root is the library itself — tracks will be re-organized in " +
      "place. Only tracks whose genre changed will move. Two tracks with the " +
      "same filename in different genre folders would collide; the second is " +
      "renamed, never replaced.",
    );
  }

  const lower = value.replace(/\\/g, "/").toLowerCase();
  const needles = ["my drive", "googledrive", "onedrive", "icloud", "dropbox"];
  for (const n of needles) {
    if (lower.includes(n)) {
      warnings.push(
        `Target root looks like a cloud-sync folder (matches '${n}'). ` +
        "Moves may be slow and may conflict with online sync. " +
        "Consider organizing to a local folder first, then syncing.",
      );
      break;
    }
  }
  return warnings;
}

function Section({
  title,
  subtitle,
  children,
}: {
  title: string;
  subtitle?: string;
  children: React.ReactNode;
}) {
  return (
    <div className="mb-6">
      <div className="flex items-baseline gap-3 mb-3">
        <h2 className="font-display font-semibold text-lg">{title}</h2>
        {subtitle && <span className="text-xs text-white/40">{subtitle}</span>}
      </div>
      <div className="panel-pad space-y-3">{children}</div>
    </div>
  );
}


/**
 * Result panel — shown after a successful organize. The user just performed a
 * destructive action across (potentially) thousands of files; they deserve a
 * real "here's what happened" screen, not just a toast that disappears.
 */
function OrganizeResultPanel({
  result,
  onViewLibrary,
  onAnother,
}: {
  result: OrganizeResult;
  onViewLibrary: () => void;
  onAnother: () => void;
}) {
  const success = result.errors.length === 0;
  const topFolders = result.folderCounts.slice(0, 10);
  const moreFolders = result.folderCounts.length - topFolders.length;

  const notify = useNotificationStore((s) => s.notify);
  const [undoing, setUndoing] = useState(false);
  const [undone, setUndone] = useState(false);
  // Per-file detail for a partial undo. The backend returns `error_messages`
  // (path + reason for each file it couldn't move back); the toast only
  // counted them. Only set when something didn't fully revert.
  const [undoResult, setUndoResult] = useState<{
    reverted: number;
    skipped: number;
    errorMessages: string[];
  } | null>(null);

  const [pruning, setPruning] = useState(false);
  const [showPruneConfirm, setShowPruneConfirm] = useState(false);
  const [pruneResult, setPruneResult] = useState<PruneEmptyFoldersResponse | null>(null);

  const handleUndo = async () => {
    if (!result.journalPath) return;
    // Register the revert as the global active op: without begin(), every
    // other view stayed enabled during the (potentially long) undo and each
    // click produced a confusing sidecar busy-rejection.
    if (useOperationStore.getState().active !== null) {
      notify("Another operation is running — wait for it to finish first.", { kind: "info" });
      return;
    }
    const ops = useOperationStore.getState();
    const opId = ops.begin("revert");
    setUndoing(true);
    try {
      const summary = await revertJournal({ journal_path: result.journalPath }, opId);
      ops.finish();
      setUndone(true);
      // Follow the files back in the in-memory library (reverse of the
      // post-execute updateTrackPaths above) so Preview / tag-apply keep
      // working without a re-scan.
      if (summary.reverted_pairs?.length) {
        const pathMap: Record<string, string> = {};
        for (const [current, restored] of summary.reverted_pairs) {
          pathMap[current] = restored;
        }
        useLibraryStore.getState().updateTrackPaths(pathMap);
      }
      const errorMessages = summary.error_messages ?? [];
      if (summary.skipped > 0 || errorMessages.length > 0) {
        setUndoResult({
          reverted: summary.reverted,
          skipped: summary.skipped,
          errorMessages,
        });
      }
      const parts = [`Restored ${summary.reverted}`];
      if (summary.skipped) parts.push(`skipped ${summary.skipped}`);
      if (summary.errors) parts.push(`${summary.errors} error(s)`);
      notify(`Undo complete — ${parts.join(", ")}`, {
        kind: summary.errors > 0 || summary.skipped > 0 ? "warning" : "success",
        detail:
          summary.skipped > 0 || summary.errors > 0
            ? "Some files couldn't be moved back — see the list below."
            : undefined,
      });
    } catch (e) {
      useOperationStore.getState().fail(e);
      if (!isCancellation(e)) {
        notify(
          typeof e === "object" && e !== null && "message" in e
            ? `Undo failed: ${String((e as { message: unknown }).message)}`
            : `Undo failed: ${String(e)}`,
          { kind: "info" },
        );
      }
    } finally {
      setUndoing(false);
    }
  };

  // --- Prune the folders this organize emptied -----------------------------
  // Deleting a directory is the most destructive thing this view does, so it
  // is never part of the organize itself: the user sees the count, confirms,
  // and only then does the sidecar remove anything (re-checking emptiness).
  const handlePrune = async () => {
    setShowPruneConfirm(false);
    if (!result.emptiedDirs.length) return;
    if (useOperationStore.getState().active !== null) {
      notify("Another operation is running — wait for it to finish first.", { kind: "info" });
      return;
    }
    setPruning(true);
    try {
      const summary = await pruneEmptyFolders({
        root: result.baseDir,
        dirs: result.emptiedDirs,
      });

      setPruneResult(summary);
      const kept = summary.skipped.length + summary.errors.length;
      notify(
        `Removed ${summary.removed.length} empty folder${summary.removed.length === 1 ? "" : "s"}` +
          (kept > 0 ? ` — ${kept} kept` : ""),
        {
          kind: summary.errors.length > 0 ? "warning" : "success",
          detail: kept > 0 ? "Folders that weren't empty are listed below." : undefined,
        },
      );
    } catch (e) {
      if (!isCancellation(e)) {
        notify(
          typeof e === "object" && e !== null && "message" in e
            ? `Couldn't remove folders: ${String((e as { message: unknown }).message)}`
            : `Couldn't remove folders: ${String(e)}`,
          { kind: "info" },
        );
      }
    } finally {
      setPruning(false);
    }
  };

  return (
    <div className="h-full overflow-auto">
      <div className="px-6 py-8 max-w-3xl mx-auto space-y-5">
        {/* Headline */}
        <div className="flex items-start gap-4">
          {success ? (
            <CheckCircle2 className="w-12 h-12 text-accent-green flex-none" />
          ) : (
            <AlertCircle className="w-12 h-12 text-accent-yellow flex-none" />
          )}
          <div className="flex-1">
            <h1 className="font-display font-semibold text-2xl text-white">
              {success ? "Library organized" : "Mostly done"}
            </h1>
            <p className="text-sm text-white/60 mt-1">
              Moved <strong className="text-white">{result.moved.toLocaleString()}</strong>{" "}
              of <strong className="text-white">{result.planned.toLocaleString()}</strong> files
              into <strong className="text-white">{result.folderCounts.length}</strong> folders.
            </p>
            <p className="text-xs text-white/40 font-mono mt-1 break-all">{result.baseDir}</p>
          </div>
        </div>

        {/* Summary stats */}
        <div className="grid grid-cols-3 gap-3">
          <Stat label="Moved" value={result.moved.toLocaleString()} accent="green" />
          <Stat
            label="Errors"
            value={result.errors.length.toLocaleString()}
            accent={result.errors.length > 0 ? "yellow" : "neutral"}
          />
          <Stat label="Destinations" value={result.folderCounts.length.toLocaleString()} accent="neutral" />
        </div>

        {/* Folder breakdown */}
        <div className="panel-pad">
          <div className="flex items-center gap-2 mb-3">
            <FolderTree className="w-4 h-4 text-accent" />
            <h2 className="font-medium text-white">Where files landed</h2>
          </div>
          <div className="space-y-1">
            {topFolders.map(([folder, count]) => {
              const pct = (count / Math.max(result.moved, 1)) * 100;
              return (
                <div key={folder} className="flex items-center gap-3 text-sm">
                  <div className="flex-1 min-w-0 truncate font-mono text-xs text-white/80">
                    {folder}
                  </div>
                  <div className="w-32 h-1.5 bg-white/5 rounded-full overflow-hidden">
                    <div className="h-full bg-accent" style={{ width: `${pct}%` }} />
                  </div>
                  <div className="text-xs text-white/50 tabular-nums w-12 text-right">
                    {count}
                  </div>
                </div>
              );
            })}
            {moreFolders > 0 && (
              <div className="text-xs text-white/40 pt-2">
                ... and {moreFolders} more folders
              </div>
            )}
          </div>
        </div>

        {/* Tag backup notice */}
        {result.backupPath && (
          <div className="panel-pad bg-accent-green/5 border-accent-green/30 text-sm">
            <div className="flex items-start gap-2">
              <CheckCircle2 className="w-4 h-4 text-accent-green flex-none mt-0.5" />
              <div>
                <div className="text-accent-green">Tag backup saved</div>
                <div className="text-xs text-white/60 mt-1 font-mono break-all">
                  {result.backupPath}
                </div>
                <div className="text-xs text-white/50 mt-1">
                  If anything looks wrong, you can restore tags from this file in the Tags tab.
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Errors (collapsible) */}
        {result.errors.length > 0 && (
          <details className="panel-pad bg-accent-yellow/5 border-accent-yellow/30">
            <summary className="cursor-pointer text-sm font-medium text-accent-yellow flex items-center gap-2">
              <AlertCircle className="w-4 h-4" />
              {result.errors.length} files couldn't be moved
            </summary>
            <ul className="mt-3 space-y-1 max-h-64 overflow-auto text-xs font-mono text-white/60">
              {result.errors.slice(0, 100).map((err, i) => (
                <li key={i} className="break-all">{err}</li>
              ))}
              {result.errors.length > 100 && (
                <li className="text-white/40">... and {result.errors.length - 100} more</li>
              )}
            </ul>
          </details>
        )}

        {/* Undo result — which files couldn't be moved back. Only shown after a
            partial undo; a clean undo leaves it hidden. */}
        {undoResult && (undoResult.errorMessages.length > 0 || undoResult.skipped > 0) && (
          <details className="panel-pad bg-accent-yellow/5 border-accent-yellow/30" open>
            <summary className="cursor-pointer text-sm font-medium text-accent-yellow flex items-center gap-2 select-none">
              <AlertCircle className="w-4 h-4 flex-none" />
              Undo left{" "}
              {undoResult.skipped + undoResult.errorMessages.length} file
              {undoResult.skipped + undoResult.errorMessages.length === 1 ? "" : "s"} in place
            </summary>
            <div className="text-xs text-white/60 mt-2">
              Moved {undoResult.reverted} back
              {undoResult.skipped > 0 && `, skipped ${undoResult.skipped}`}
              {undoResult.errorMessages.length > 0 &&
                `, ${undoResult.errorMessages.length} error${
                  undoResult.errorMessages.length === 1 ? "" : "s"
                }`}
              . Skipped files were left where they are because the original path
              was occupied or the file was already moved.
            </div>
            {undoResult.errorMessages.length > 0 && (
              <ul className="mt-2 space-y-1 max-h-56 overflow-auto text-[11px] font-mono text-white/60 bg-black/20 rounded-sm p-2">
                {undoResult.errorMessages.slice(0, 100).map((m, i) => (
                  <li key={i} className="break-all">{m}</li>
                ))}
                {undoResult.errorMessages.length > 100 && (
                  <li className="text-white/40 italic">
                    …and {undoResult.errorMessages.length - 100} more
                  </li>
                )}
              </ul>
            )}
          </details>
        )}

        {/* Folders this organize emptied. Re-filing a sorted library moves the
            last track out of a genre folder and leaves the folder behind. We
            never delete one as part of the organize — offer it, with the list
            visible, and let the user decide. Hidden once undone: undo puts the
            files back, so the folders aren't empty any more. */}
        {result.emptiedDirs.length > 0 && !undone && !pruneResult && (
          <div className="panel-pad space-y-2">
            <div className="text-sm text-white">
              {result.emptiedDirs.length} folder
              {result.emptiedDirs.length === 1 ? " is" : "s are"} now empty
            </div>
            <p className="text-xs text-white/50">
              Every track moved out of{" "}
              {result.emptiedDirs.length === 1 ? "this folder" : "these folders"}. Removing
              them is optional and only removes the folders themselves — never a file.
            </p>
            <details className="text-xs">
              <summary className="cursor-pointer text-white/60 hover:text-white">
                Show folders
              </summary>
              <ul className="mt-2 space-y-0.5 font-mono text-white/50 max-h-40 overflow-auto">
                {result.emptiedDirs.map((d) => (
                  <li key={d} className="break-all">{d}</li>
                ))}
              </ul>
            </details>
            <button
              className="btn-ghost"
              onClick={() => setShowPruneConfirm(true)}
              disabled={pruning}
            >
              {pruning ? <Loader2 className="w-4 h-4 animate-spin" /> : <FolderTree className="w-4 h-4" />}
              Remove empty folders
            </button>
          </div>
        )}

        {pruneResult && (
          <div className="panel-pad space-y-2">
            <div className="text-sm text-white">
              Removed {pruneResult.removed.length} empty folder
              {pruneResult.removed.length === 1 ? "" : "s"}
            </div>
            {(pruneResult.skipped.length > 0 || pruneResult.errors.length > 0) && (
              <details className="text-xs" open>
                <summary className="cursor-pointer text-accent-yellow">
                  {pruneResult.skipped.length + pruneResult.errors.length} kept
                </summary>
                <ul className="mt-2 space-y-0.5 text-white/60 max-h-40 overflow-auto">
                  {pruneResult.skipped.map((s) => (
                    <li key={s.path} className="break-all">
                      <span className="font-mono">{s.path}</span> — {s.reason}
                    </li>
                  ))}
                  {pruneResult.errors.map((e) => (
                    <li key={e} className="break-all text-accent-yellow">{e}</li>
                  ))}
                </ul>
              </details>
            )}
          </div>
        )}

        <ConfirmModal
          open={showPruneConfirm}
          variant="danger"
          destructive
          title="Remove empty folders?"
          message={
            `${result.emptiedDirs.length} folder${result.emptiedDirs.length === 1 ? "" : "s"} ` +
            "will be removed. Only the folders go — no files are deleted, and any folder " +
            "that isn't actually empty is left alone. This is not covered by Undo."
          }
          confirmLabel="Remove folders"
          onConfirm={handlePrune}
          onCancel={() => setShowPruneConfirm(false)}
        />

        {/* Actions */}
        <div className="flex items-center gap-2 pt-4">
          {result.journalPath && result.moved > 0 && (
            <button
              className="btn-ghost text-accent-yellow"
              onClick={handleUndo}
              disabled={undoing || undone}
              title="Move every file back to where it was before this organize"
            >
              {undoing ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Undo2 className="w-4 h-4" />
              )}
              {undone ? "Undone" : "Undo this organize"}
            </button>
          )}
          <div className="flex-1" />
          <button className="btn-ghost" onClick={onAnother}>
            <RotateCcw className="w-4 h-4" />
            Organize another folder
          </button>
          <button className="btn-primary" onClick={onViewLibrary}>
            <Eye className="w-4 h-4" />
            View library
          </button>
        </div>
      </div>
    </div>
  );
}

function Stat({
  label,
  value,
  accent,
}: {
  label: string;
  value: string;
  accent: "green" | "yellow" | "neutral";
}) {
  const colorClass = {
    green: "text-accent-green",
    yellow: "text-accent-yellow",
    neutral: "text-white",
  }[accent];
  return (
    <div className="panel-pad">
      <div className="label">{label}</div>
      <div className={`text-2xl font-display font-semibold tabular-nums ${colorClass}`}>
        {value}
      </div>
    </div>
  );
}
